export const API_ROUTES = {
    mission_vision: "/api/v1/mission-vision",
    faq: "/api/v1/faq",
    event: "/api/v1/event",
    testimonial: "/api/v1/testimonial",
    counter: "/api/v1/counter",
    feature: "/api/v1/feature",
    achiever: "/api/v1/achiever",
    aboutSection: "/api/v1/about-section",
    bannerSection: "/api/v1/home-page-banner",
    blog: "/api/v1/blog",
    expertTip: "/api/v1/expert-tip",
    management: "/api/v1/team-member/management",
    staff: "/api/v1/team-member/staff",
};