export const API_ROUTES = {
    mission_vision: "/api/v1/mission-vision",
    faq: "/api/v1/faq",
    gallery: "/api/v1/gallery",
    event: "/api/v1/event",
    testimonial: "/api/v1/testimonial",
    counter: "/api/v1/counter",
    feature: "/api/v1/feature",
    achieverCategory: "/api/v1/achiever/category",
    achieverStudent: "/api/v1/achiever/student",
    aboutSection: "/api/v1/about-section",
    bannerSection: "/api/v1/home-page-banner",
    blog: "/api/v1/blog",
    expertTip: "/api/v1/expert-tip",
    management: "/api/v1/team-member/management",
    staff: "/api/v1/team-member/staff",
    contact: "/api/v1/contact-form",
    register: "/api/v1/auth/register",
    forgot_password: "/api/v1/auth/forgot-password",
    admission_puc: "/api/v1/admission/puc",
    password_update: "/api/v1/profile/update-password",
    profile_update: "/api/v1/profile/update",
    admission_not_puc: "/api/v1/admission/not-puc",
};